const REPORTS = [
  { name: 'Central Library · Fire drill', date: '29 Sep 2026', type: 'Fire', cleared: '04:18', safety: '92', status: 'SIMULATED' },
  { name: 'Research wing · Gas leak', date: '24 Sep 2026', type: 'Gas', cleared: '05:06', safety: '86', status: 'SIMULATED' },
  { name: 'Assembly hall · Egress test', date: '18 Sep 2026', type: 'Crowd flow', cleared: '07:35', safety: '81', status: 'SIMULATED' },
  { name: 'Atrium · Water ingress', date: '12 Sep 2026', type: 'Flood', cleared: '06:20', safety: '89', status: 'SIMULATED' }
];

export function renderReportsPage() {
  const rows = REPORTS.map((row, index) => `<tr><td><span class="report-row-icon">${['♨','◉','⠿','≈'][index]}</span><span class="report-row-name"><b>${row.name}</b><small>${row.date}</small></span></td><td>${row.type}</td><td class="report-duration">${row.cleared}</td><td><span class="report-score">${row.safety}</span><small class="score-max"> / 100</small></td><td><span class="report-status"><i></i>${row.status}</span></td><td><button class="row-more" data-action="report-menu" aria-label="Report options">···</button></td></tr>`).join('');
  return `
    <section class="page-view-content">
      <div class="page-breadcrumb-label">INTELLIGENCE / DRILL HISTORY</div>
      <div class="content-heading"><div><h1>Reports & insights<span>.</span></h1><p>Review drill outcomes and spot opportunities to strengthen your plan.</p></div><button class="page-action-button" data-action="export-reports">↓ &nbsp; Export report</button></div>
      <div class="report-kpi-grid"><article><span>DRILLS RUN</span><b>12</b><small class="kpi-trend">↑ 3 this month</small><div class="kpi-spark teal">▁▂▃▂▄▅▃▆</div></article><article><span>AVG. CLEARANCE</span><b>05:42</b><small class="kpi-trend">↓ 18% vs first drill</small><div class="kpi-spark violet">▂▃▂▄▃▅▄▆</div></article><article><span>AVG. SAFETY SCORE</span><b>87<span>/100</span></b><small class="kpi-trend">↑ 6 points</small><div class="kpi-spark orange">▁▂▃▄▃▅▆▇</div></article><article><span>ROUTES COMPARED</span><b>36</b><small class="kpi-trend neutral">3 strategies per drill</small><div class="kpi-spark blue">▂▃▃▄▅▄▆▇</div></article></div>
      <div class="reports-grid"><article class="page-card trend-card"><div class="page-card-heading"><div><div class="section-kicker">PERFORMANCE TREND</div><h2>Clearance time by drill</h2></div><button class="report-period" data-action="report-period">Last 30 days⌄</button></div><div class="chart-legend"><span><i></i>Best route</span><span><i class="legend-baseline"></i>Baseline</span></div><div class="chart-container"><div class="chart-y-axis"><span>08:00</span><span>06:00</span><span>04:00</span><span>02:00</span></div><svg class="report-chart" viewBox="0 0 760 220" role="img" aria-label="Illustrative clearance time trend"><g class="chart-grid"><path d="M0 15H760M0 72H760M0 129H760M0 186H760"/></g><path class="chart-baseline" d="M12 50 120 64 228 51 336 83 444 78 552 101 660 93 748 116"/><path class="chart-area" d="M12 94 120 109 228 98 336 131 444 123 552 150 660 143 748 164V186H12Z"/><path class="chart-line" d="M12 94 120 109 228 98 336 131 444 123 552 150 660 143 748 164"/><g class="chart-points"><circle cx="12" cy="94" r="4"/><circle cx="120" cy="109" r="4"/><circle cx="228" cy="98" r="4"/><circle cx="336" cy="131" r="4"/><circle cx="444" cy="123" r="4"/><circle cx="552" cy="150" r="4"/><circle cx="660" cy="143" r="4"/><circle cx="748" cy="164" r="4"/></g><g class="chart-labels"><text x="12" y="209">SEP 02</text><text x="120" y="209">SEP 06</text><text x="228" y="209">SEP 10</text><text x="336" y="209">SEP 14</text><text x="444" y="209">SEP 18</text><text x="552" y="209">SEP 22</text><text x="660" y="209">SEP 26</text><text x="748" y="209">TODAY</text></g></svg></div><div class="trend-callout"><span>✳</span> Dynamic routing improved median clearance by <b>18%</b> across these illustrative drills.</div></article><article class="page-card insight-card"><div class="section-kicker">AI-ASSISTED OBSERVATION</div><h2>What the drills suggest</h2><div class="insight-item"><span class="insight-icon teal">↗</span><div><b>East exits carry the most load</b><p>Consider testing a balanced route split in the next exercise.</p></div></div><div class="insight-item"><span class="insight-icon amber">⌁</span><div><b>Smoke affects two connected zones</b><p>Review the reading hall and archive door assumptions.</p></div></div><div class="insight-item"><span class="insight-icon violet">◷</span><div><b>First-floor data needs a review</b><p>Verify stairwell and exit details in the building model.</p></div></div><div class="insight-disclaimer">DEMO OBSERVATIONS · VERIFY AGAINST REAL BUILDING DATA</div></article></div>
      <article class="page-card report-table-card"><div class="page-card-heading"><div><div class="section-kicker">RECENT EXERCISES</div><h2>Drill report history</h2></div><button class="page-subtle-button" data-action="view-all-reports">View all <span>→</span></button></div><div class="table-scroll"><table class="report-table"><thead><tr><th>SCENARIO</th><th>HAZARD</th><th>CLEAR TIME</th><th>SAFETY SCORE</th><th>DATA TYPE</th><th></th></tr></thead><tbody>${rows}</tbody></table></div></article>
      <div class="demo-note"><span>i</span><p><b>Demo analytics.</b> Report metrics and trends are sample values for the interface prototype, not results from a validated building simulation.</p></div>
    </section>`;
}
