export function renderSettingsPage() {
  return `
    <section class="page-view-content">
      <div class="page-breadcrumb-label">WORKSPACE / CONFIGURATION</div>
      <div class="content-heading"><div><h1>Settings<span>.</span></h1><p>Configure your demo workspace and review the data boundaries.</p></div><button class="page-action-button" data-action="save-settings">✓ &nbsp; Save changes</button></div>
      <div class="settings-layout"><nav class="settings-nav" aria-label="Settings sections"><a class="selected" href="#general-settings">◈ <span>General</span></a><a href="#simulation-settings">⌁ <span>Simulation</span></a><a href="#data-settings">▤ <span>Data & privacy</span></a><a href="#notifications-settings">♧ <span>Notifications</span></a></nav><div class="settings-content">
        <section class="page-card settings-card" id="general-settings"><div class="settings-card-heading"><div><div class="section-kicker">WORKSPACE PROFILE</div><h2>General</h2></div></div><div class="settings-form-grid"><label>Workspace name<input value="Vistaraz" data-setting-field="workspaceName" /></label><label>Project name<input value="SafeTwin AI" data-setting-field="projectName" /></label><label>Primary location<input value="Vadodara, Gujarat" data-setting-field="location" /></label><label>Preferred units<select data-setting-field="units"><option>Metric (m², km/h)</option><option>Imperial (ft², mph)</option></select></label></div></section>
        <section class="page-card settings-card" id="simulation-settings"><div class="settings-card-heading"><div><div class="section-kicker">DEFAULT BEHAVIOUR</div><h2>Simulation preferences</h2></div></div><div class="setting-row"><div><b>Start drills paused</b><small>Review scenario settings before the simulation begins.</small></div><button class="switch" role="switch" aria-checked="false" data-setting-toggle><i></i></button></div><div class="setting-row"><div><b>Show hazard heatmap</b><small>Display the illustrative heat overlay by default.</small></div><button class="switch on" role="switch" aria-checked="true" data-setting-toggle><i></i></button></div><div class="setting-row"><div><b>Include route recommendations</b><small>Show suggested paths in the digital-twin view.</small></div><button class="switch on" role="switch" aria-checked="true" data-setting-toggle><i></i></button></div></section>
        <section class="page-card settings-card" id="data-settings"><div class="settings-card-heading"><div><div class="section-kicker">DATA BOUNDARIES</div><h2>Data & privacy</h2></div><span class="privacy-badge"><i></i> CAMERA NOT CONNECTED</span></div><div class="privacy-callout"><span>◎</span><div><b>CCTV integration is a future roadmap item</b><p>This prototype has no camera feed and does not collect real occupant data. Any future integration should require authorization, privacy review and clear data-retention rules.</p></div></div><div class="setting-row"><div><b>Use synthetic demo data</b><small>Current simulation occupants are generated locally in the browser.</small></div><span class="locked-label">ON · DEMO</span></div><div class="setting-row"><div><b>Person identification</b><small>Not implemented. Future design should use aggregate counts only.</small></div><span class="locked-label muted-lock">NOT ENABLED</span></div></section>
        <section class="page-card settings-card" id="notifications-settings"><div class="settings-card-heading"><div><div class="section-kicker">UPDATES</div><h2>Notifications</h2></div></div><div class="setting-row"><div><b>Scenario completion</b><small>Show a local notification when a demo drill completes.</small></div><button class="switch on" role="switch" aria-checked="true" data-setting-toggle><i></i></button></div><div class="setting-row"><div><b>Risk threshold alerts</b><small>Highlight when the illustrative risk score changes.</small></div><button class="switch on" role="switch" aria-checked="true" data-setting-toggle><i></i></button></div></section>
        <div class="settings-save-row"><span><i></i> Your changes are stored in this demo session only.</span><button class="page-action-button" data-action="save-settings">Save changes</button></div>
      </div></div>
    </section>`;
}
